# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preamble',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
