# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_preamble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preamble',
        ),
    ]
